[package]
name = "repo"
description = "An opinionated tool for repo management."
version = "0.15.4-dev"
edition = "2021"
license = "MIT"
exclude = [
  "src/templates/node_modules",
  # TODO: The following is gone, but we're keeping it around for now in case it
  # appears from an old checkout.
  "src/templates/workaround-indirection-folder/node_modules",
]
repository = "https://github.com/lgarron/repo"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
clap_complete = "4.5.38"
